//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormPipe.LTA.Contracts.ServiceContracts
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportPreservationObjectRequest", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class ImportPreservationObjectRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] ChunkField;
        
        private int ChunkSizeField;
        
        private string FileExtensionField;
        
        private string FileSetIdField;
        
        private string SubmissionAgreementIdField;
        
        private long TotalFileSizeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Chunk
        {
            get
            {
                return this.ChunkField;
            }
            set
            {
                this.ChunkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChunkSize
        {
            get
            {
                return this.ChunkSizeField;
            }
            set
            {
                this.ChunkSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileExtension
        {
            get
            {
                return this.FileExtensionField;
            }
            set
            {
                this.FileExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileSetId
        {
            get
            {
                return this.FileSetIdField;
            }
            set
            {
                this.FileSetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionAgreementId
        {
            get
            {
                return this.SubmissionAgreementIdField;
            }
            set
            {
                this.SubmissionAgreementIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalFileSize
        {
            get
            {
                return this.TotalFileSizeField;
            }
            set
            {
                this.TotalFileSizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportPreservationObjectResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class ImportPreservationObjectResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfo
        {
            get
            {
                return this.ErrorInfoField;
            }
            set
            {
                this.ErrorInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorInfo", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class ErrorInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorCodeField;
        
        private int ErrorIdField;
        
        private string ErrorMessageField;
        
        private string LoggedUserNameField;
        
        private string ServiceNameField;
        
        private System.Nullable<System.DateTime> TimestampField;
        
        private bool TimestampSpecifiedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorId
        {
            get
            {
                return this.ErrorIdField;
            }
            set
            {
                this.ErrorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoggedUserName
        {
            get
            {
                return this.LoggedUserNameField;
            }
            set
            {
                this.LoggedUserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName
        {
            get
            {
                return this.ServiceNameField;
            }
            set
            {
                this.ServiceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TimestampSpecified
        {
            get
            {
                return this.TimestampSpecifiedField;
            }
            set
            {
                this.TimestampSpecifiedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportMetadataFileRequest", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class ImportMetadataFileRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] ChunkField;
        
        private int ChunkSizeField;
        
        private string EncodingField;
        
        private string FileSetIdField;
        
        private string SubmissionAgreementIdField;
        
        private long TotalFileSizeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Chunk
        {
            get
            {
                return this.ChunkField;
            }
            set
            {
                this.ChunkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChunkSize
        {
            get
            {
                return this.ChunkSizeField;
            }
            set
            {
                this.ChunkSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Encoding
        {
            get
            {
                return this.EncodingField;
            }
            set
            {
                this.EncodingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileSetId
        {
            get
            {
                return this.FileSetIdField;
            }
            set
            {
                this.FileSetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionAgreementId
        {
            get
            {
                return this.SubmissionAgreementIdField;
            }
            set
            {
                this.SubmissionAgreementIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalFileSize
        {
            get
            {
                return this.TotalFileSizeField;
            }
            set
            {
                this.TotalFileSizeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportMetadataFileResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class ImportMetadataFileResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfo
        {
            get
            {
                return this.ErrorInfoField;
            }
            set
            {
                this.ErrorInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportMetadataRequest", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class ImportMetadataRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FileSetIdField;
        
        private string MetadataXmlField;
        
        private string SubmissionAgreementIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileSetId
        {
            get
            {
                return this.FileSetIdField;
            }
            set
            {
                this.FileSetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MetadataXml
        {
            get
            {
                return this.MetadataXmlField;
            }
            set
            {
                this.MetadataXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionAgreementId
        {
            get
            {
                return this.SubmissionAgreementIdField;
            }
            set
            {
                this.SubmissionAgreementIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportMetadataResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class ImportMetadataResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfo
        {
            get
            {
                return this.ErrorInfoField;
            }
            set
            {
                this.ErrorInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplyImportRequest", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class ApplyImportRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ConfidentialityDegradationDateField;
        
        private int ConfidentialityLevelField;
        
        private string DataSubmissionSessionField;
        
        private string DeliverySpecificationField;
        
        private string DeliveryTypeField;
        
        private string FileSetIdField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.FileSetRelation[] FileSetRelationsField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.FileInfo[] FilesField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ImportMode ImportModeField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.Checksum MetadataChecksumField;
        
        private bool PersonalDataFlagField;
        
        private string SubmissionAgreementIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ConfidentialityDegradationDate
        {
            get
            {
                return this.ConfidentialityDegradationDateField;
            }
            set
            {
                this.ConfidentialityDegradationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfidentialityLevel
        {
            get
            {
                return this.ConfidentialityLevelField;
            }
            set
            {
                this.ConfidentialityLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSubmissionSession
        {
            get
            {
                return this.DataSubmissionSessionField;
            }
            set
            {
                this.DataSubmissionSessionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliverySpecification
        {
            get
            {
                return this.DeliverySpecificationField;
            }
            set
            {
                this.DeliverySpecificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryType
        {
            get
            {
                return this.DeliveryTypeField;
            }
            set
            {
                this.DeliveryTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileSetId
        {
            get
            {
                return this.FileSetIdField;
            }
            set
            {
                this.FileSetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.FileSetRelation[] FileSetRelations
        {
            get
            {
                return this.FileSetRelationsField;
            }
            set
            {
                this.FileSetRelationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.FileInfo[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ImportMode ImportMode
        {
            get
            {
                return this.ImportModeField;
            }
            set
            {
                this.ImportModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.Checksum MetadataChecksum
        {
            get
            {
                return this.MetadataChecksumField;
            }
            set
            {
                this.MetadataChecksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PersonalDataFlag
        {
            get
            {
                return this.PersonalDataFlagField;
            }
            set
            {
                this.PersonalDataFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionAgreementId
        {
            get
            {
                return this.SubmissionAgreementIdField;
            }
            set
            {
                this.SubmissionAgreementIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Checksum", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class Checksum : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AlgorithmField;
        
        private byte[] ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Algorithm
        {
            get
            {
                return this.AlgorithmField;
            }
            set
            {
                this.AlgorithmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileSetRelation", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class FileSetRelation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ArchiveNameField;
        
        private System.Guid FileSetField;
        
        private string TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveName
        {
            get
            {
                return this.ArchiveNameField;
            }
            set
            {
                this.ArchiveNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FileSet
        {
            get
            {
                return this.FileSetField;
            }
            set
            {
                this.FileSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileInfo", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class FileInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.Checksum ChecksumField;
        
        private string FileIdField;
        
        private string OriginalFileIdField;
        
        private string OriginalFileNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.Checksum Checksum
        {
            get
            {
                return this.ChecksumField;
            }
            set
            {
                this.ChecksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileId
        {
            get
            {
                return this.FileIdField;
            }
            set
            {
                this.FileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalFileId
        {
            get
            {
                return this.OriginalFileIdField;
            }
            set
            {
                this.OriginalFileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalFileName
        {
            get
            {
                return this.OriginalFileNameField;
            }
            set
            {
                this.OriginalFileNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportMode", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public enum ImportMode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COMPLETE_FS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        METADATAANDHASH_FS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WITHOUTHASH_FS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        METADATAWITHOUTCHECKSUM_FS = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplyImportResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class ApplyImportResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.DataContracts.Security.PackageScanningResult DetectedThreatsField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfoField;
        
        private string ImportedFileSetIdField;
        
        private FormPipe.LTA.Contracts.Exceptions.MetadataValidationError[] MetadataValidationErrorsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.DataContracts.Security.PackageScanningResult DetectedThreats
        {
            get
            {
                return this.DetectedThreatsField;
            }
            set
            {
                this.DetectedThreatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfo
        {
            get
            {
                return this.ErrorInfoField;
            }
            set
            {
                this.ErrorInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImportedFileSetId
        {
            get
            {
                return this.ImportedFileSetIdField;
            }
            set
            {
                this.ImportedFileSetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.Exceptions.MetadataValidationError[] MetadataValidationErrors
        {
            get
            {
                return this.MetadataValidationErrorsField;
            }
            set
            {
                this.MetadataValidationErrorsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestImportRequest", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class TestImportRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ConfidentialityDegradationDateField;
        
        private int ConfidentialityLevelField;
        
        private string DataSubmissionSessionField;
        
        private string FileSetIdField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.FileInfo[] FilesField;
        
        private int HashChecksumAlgIdField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ImportMode ImportModeField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.Checksum MetadataChecksumField;
        
        private int MetadataChecksumAlgIdField;
        
        private bool PersonalDataFlagField;
        
        private string SubmissionAgreementIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ConfidentialityDegradationDate
        {
            get
            {
                return this.ConfidentialityDegradationDateField;
            }
            set
            {
                this.ConfidentialityDegradationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfidentialityLevel
        {
            get
            {
                return this.ConfidentialityLevelField;
            }
            set
            {
                this.ConfidentialityLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSubmissionSession
        {
            get
            {
                return this.DataSubmissionSessionField;
            }
            set
            {
                this.DataSubmissionSessionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileSetId
        {
            get
            {
                return this.FileSetIdField;
            }
            set
            {
                this.FileSetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.FileInfo[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HashChecksumAlgId
        {
            get
            {
                return this.HashChecksumAlgIdField;
            }
            set
            {
                this.HashChecksumAlgIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ImportMode ImportMode
        {
            get
            {
                return this.ImportModeField;
            }
            set
            {
                this.ImportModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.Checksum MetadataChecksum
        {
            get
            {
                return this.MetadataChecksumField;
            }
            set
            {
                this.MetadataChecksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MetadataChecksumAlgId
        {
            get
            {
                return this.MetadataChecksumAlgIdField;
            }
            set
            {
                this.MetadataChecksumAlgIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PersonalDataFlag
        {
            get
            {
                return this.PersonalDataFlagField;
            }
            set
            {
                this.PersonalDataFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionAgreementId
        {
            get
            {
                return this.SubmissionAgreementIdField;
            }
            set
            {
                this.SubmissionAgreementIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestImportResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class TestImportResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfoField;
        
        private bool ResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfo
        {
            get
            {
                return this.ErrorInfoField;
            }
            set
            {
                this.ErrorInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestMetadataRequest", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class TestMetadataRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime ConfidentialityDegradationDateField;
        
        private int ConfidentialityLevelField;
        
        private string DataSubmissionSessionField;
        
        private string FileSetIdField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.FileInfo[] FilesField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.Checksum MetadataChecksumField;
        
        private bool PersonalDataFlagField;
        
        private string SubmissionAgreementIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ConfidentialityDegradationDate
        {
            get
            {
                return this.ConfidentialityDegradationDateField;
            }
            set
            {
                this.ConfidentialityDegradationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfidentialityLevel
        {
            get
            {
                return this.ConfidentialityLevelField;
            }
            set
            {
                this.ConfidentialityLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSubmissionSession
        {
            get
            {
                return this.DataSubmissionSessionField;
            }
            set
            {
                this.DataSubmissionSessionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileSetId
        {
            get
            {
                return this.FileSetIdField;
            }
            set
            {
                this.FileSetIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.FileInfo[] Files
        {
            get
            {
                return this.FilesField;
            }
            set
            {
                this.FilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.Checksum MetadataChecksum
        {
            get
            {
                return this.MetadataChecksumField;
            }
            set
            {
                this.MetadataChecksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PersonalDataFlag
        {
            get
            {
                return this.PersonalDataFlagField;
            }
            set
            {
                this.PersonalDataFlagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionAgreementId
        {
            get
            {
                return this.SubmissionAgreementIdField;
            }
            set
            {
                this.SubmissionAgreementIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestMetadataResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class TestMetadataResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfoField;
        
        private bool ResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfo
        {
            get
            {
                return this.ErrorInfoField;
            }
            set
            {
                this.ErrorInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllSubmissionAgreementsResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class GetAllSubmissionAgreementsResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfoField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.SubmissionAgreementInfo[] SubmissionAgreementsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfo
        {
            get
            {
                return this.ErrorInfoField;
            }
            set
            {
                this.ErrorInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.SubmissionAgreementInfo[] SubmissionAgreements
        {
            get
            {
                return this.SubmissionAgreementsField;
            }
            set
            {
                this.SubmissionAgreementsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubmissionAgreementInfo", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class SubmissionAgreementInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private string IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllChecksumAlgorithmsRequest", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class GetAllChecksumAlgorithmsRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SubmissionAgreementIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionAgreementId
        {
            get
            {
                return this.SubmissionAgreementIdField;
            }
            set
            {
                this.SubmissionAgreementIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetAllChecksumAlgorithmsResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class GetAllChecksumAlgorithmsResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] ChecksumAlgorithmsField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ChecksumAlgorithms
        {
            get
            {
                return this.ChecksumAlgorithmsField;
            }
            set
            {
                this.ChecksumAlgorithmsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfo
        {
            get
            {
                return this.ErrorInfoField;
            }
            set
            {
                this.ErrorInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemVersionInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class SystemVersionInfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.SystemVersionInfo SystemVersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.SystemVersionInfo SystemVersion
        {
            get
            {
                return this.SystemVersionField;
            }
            set
            {
                this.SystemVersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemVersionInfo", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class SystemVersionInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BuildVersionField;
        
        private int MajorVersionField;
        
        private int MinorVersionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BuildVersion
        {
            get
            {
                return this.BuildVersionField;
            }
            set
            {
                this.BuildVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MajorVersion
        {
            get
            {
                return this.MajorVersionField;
            }
            set
            {
                this.MajorVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinorVersion
        {
            get
            {
                return this.MinorVersionField;
            }
            set
            {
                this.MinorVersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RollbackIngestionRequest", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class RollbackIngestionRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AipIdField;
        
        private string SubmissionAgreementIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AipId
        {
            get
            {
                return this.AipIdField;
            }
            set
            {
                this.AipIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionAgreementId
        {
            get
            {
                return this.SubmissionAgreementIdField;
            }
            set
            {
                this.SubmissionAgreementIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RollbackIngestionResponse", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.ServiceContracts")]
    public partial class RollbackIngestionResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfoField;
        
        private bool ResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FormPipe.LTA.Contracts.ServiceContracts.ErrorInfo ErrorInfo
        {
            get
            {
                return this.ErrorInfoField;
            }
            set
            {
                this.ErrorInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
}
namespace FormPipe.LTA.Contracts.DataContracts.Security
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PackageScanningResult", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.DataContracts.Secu" +
        "rity")]
    public partial class PackageScanningResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] InfectedFilesField;
        
        private bool IsMetadataInfectedField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] InfectedFiles
        {
            get
            {
                return this.InfectedFilesField;
            }
            set
            {
                this.InfectedFilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMetadataInfected
        {
            get
            {
                return this.IsMetadataInfectedField;
            }
            set
            {
                this.IsMetadataInfectedField = value;
            }
        }
    }
}
namespace FormPipe.LTA.Contracts.Exceptions
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetadataValidationError", Namespace="http://schemas.datacontract.org/2004/07/FormPipe.LTA.Contracts.Exceptions")]
    public partial struct MetadataValidationError : System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorField;
        
        private string NamespaceField;
        
        private string NodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namespace
        {
            get
            {
                return this.NamespaceField;
            }
            set
            {
                this.NamespaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Node
        {
            get
            {
                return this.NodeField;
            }
            set
            {
                this.NodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IImportWebService")]
public interface IImportWebService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/ImportPreservationObject", ReplyAction="http://tempuri.org/IImportWebService/ImportPreservationObjectResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.ImportPreservationObjectResponse ImportPreservationObject(FormPipe.LTA.Contracts.ServiceContracts.ImportPreservationObjectRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/ImportPreservationObject", ReplyAction="http://tempuri.org/IImportWebService/ImportPreservationObjectResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.ImportPreservationObjectResponse> ImportPreservationObjectAsync(FormPipe.LTA.Contracts.ServiceContracts.ImportPreservationObjectRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/ImportMetadataFile", ReplyAction="http://tempuri.org/IImportWebService/ImportMetadataFileResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataFileResponse ImportMetadataFile(FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataFileRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/ImportMetadataFile", ReplyAction="http://tempuri.org/IImportWebService/ImportMetadataFileResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataFileResponse> ImportMetadataFileAsync(FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataFileRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/ImportMetadata", ReplyAction="http://tempuri.org/IImportWebService/ImportMetadataResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataResponse ImportMetadata(FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/ImportMetadata", ReplyAction="http://tempuri.org/IImportWebService/ImportMetadataResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataResponse> ImportMetadataAsync(FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/ApplyImport", ReplyAction="http://tempuri.org/IImportWebService/ApplyImportResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.ApplyImportResponse ApplyImport(FormPipe.LTA.Contracts.ServiceContracts.ApplyImportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/ApplyImport", ReplyAction="http://tempuri.org/IImportWebService/ApplyImportResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.ApplyImportResponse> ApplyImportAsync(FormPipe.LTA.Contracts.ServiceContracts.ApplyImportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/TestImport", ReplyAction="http://tempuri.org/IImportWebService/TestImportResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.TestImportResponse TestImport(FormPipe.LTA.Contracts.ServiceContracts.TestImportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/TestImport", ReplyAction="http://tempuri.org/IImportWebService/TestImportResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.TestImportResponse> TestImportAsync(FormPipe.LTA.Contracts.ServiceContracts.TestImportRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/TestMetadata", ReplyAction="http://tempuri.org/IImportWebService/TestMetadataResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.TestMetadataResponse TestMetadata(FormPipe.LTA.Contracts.ServiceContracts.TestMetadataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/TestMetadata", ReplyAction="http://tempuri.org/IImportWebService/TestMetadataResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.TestMetadataResponse> TestMetadataAsync(FormPipe.LTA.Contracts.ServiceContracts.TestMetadataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/GetAllSubmissionAgreements", ReplyAction="http://tempuri.org/IImportWebService/GetAllSubmissionAgreementsResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.GetAllSubmissionAgreementsResponse GetAllSubmissionAgreements();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/GetAllSubmissionAgreements", ReplyAction="http://tempuri.org/IImportWebService/GetAllSubmissionAgreementsResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.GetAllSubmissionAgreementsResponse> GetAllSubmissionAgreementsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/GetAllChecksumAlgorithms", ReplyAction="http://tempuri.org/IImportWebService/GetAllChecksumAlgorithmsResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.GetAllChecksumAlgorithmsResponse GetAllChecksumAlgorithms(FormPipe.LTA.Contracts.ServiceContracts.GetAllChecksumAlgorithmsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/GetAllChecksumAlgorithms", ReplyAction="http://tempuri.org/IImportWebService/GetAllChecksumAlgorithmsResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.GetAllChecksumAlgorithmsResponse> GetAllChecksumAlgorithmsAsync(FormPipe.LTA.Contracts.ServiceContracts.GetAllChecksumAlgorithmsRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/GetSystemVersion", ReplyAction="http://tempuri.org/IImportWebService/GetSystemVersionResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.SystemVersionInfoResponse GetSystemVersion();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/GetSystemVersion", ReplyAction="http://tempuri.org/IImportWebService/GetSystemVersionResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.SystemVersionInfoResponse> GetSystemVersionAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/RollbackIngestion", ReplyAction="http://tempuri.org/IImportWebService/RollbackIngestionResponse")]
    FormPipe.LTA.Contracts.ServiceContracts.RollbackIngestionResponse RollbackIngestion(FormPipe.LTA.Contracts.ServiceContracts.RollbackIngestionRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportWebService/RollbackIngestion", ReplyAction="http://tempuri.org/IImportWebService/RollbackIngestionResponse")]
    System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.RollbackIngestionResponse> RollbackIngestionAsync(FormPipe.LTA.Contracts.ServiceContracts.RollbackIngestionRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IImportWebServiceChannel : IImportWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ImportWebServiceClient : System.ServiceModel.ClientBase<IImportWebService>, IImportWebService
{
    
    public ImportWebServiceClient()
    {
    }
    
    public ImportWebServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ImportWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImportWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImportWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.ImportPreservationObjectResponse ImportPreservationObject(FormPipe.LTA.Contracts.ServiceContracts.ImportPreservationObjectRequest request)
    {
        return base.Channel.ImportPreservationObject(request);
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.ImportPreservationObjectResponse> ImportPreservationObjectAsync(FormPipe.LTA.Contracts.ServiceContracts.ImportPreservationObjectRequest request)
    {
        return base.Channel.ImportPreservationObjectAsync(request);
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataFileResponse ImportMetadataFile(FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataFileRequest request)
    {
        return base.Channel.ImportMetadataFile(request);
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataFileResponse> ImportMetadataFileAsync(FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataFileRequest request)
    {
        return base.Channel.ImportMetadataFileAsync(request);
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataResponse ImportMetadata(FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataRequest request)
    {
        return base.Channel.ImportMetadata(request);
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataResponse> ImportMetadataAsync(FormPipe.LTA.Contracts.ServiceContracts.ImportMetadataRequest request)
    {
        return base.Channel.ImportMetadataAsync(request);
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.ApplyImportResponse ApplyImport(FormPipe.LTA.Contracts.ServiceContracts.ApplyImportRequest request)
    {
        return base.Channel.ApplyImport(request);
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.ApplyImportResponse> ApplyImportAsync(FormPipe.LTA.Contracts.ServiceContracts.ApplyImportRequest request)
    {
        return base.Channel.ApplyImportAsync(request);
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.TestImportResponse TestImport(FormPipe.LTA.Contracts.ServiceContracts.TestImportRequest request)
    {
        return base.Channel.TestImport(request);
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.TestImportResponse> TestImportAsync(FormPipe.LTA.Contracts.ServiceContracts.TestImportRequest request)
    {
        return base.Channel.TestImportAsync(request);
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.TestMetadataResponse TestMetadata(FormPipe.LTA.Contracts.ServiceContracts.TestMetadataRequest request)
    {
        return base.Channel.TestMetadata(request);
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.TestMetadataResponse> TestMetadataAsync(FormPipe.LTA.Contracts.ServiceContracts.TestMetadataRequest request)
    {
        return base.Channel.TestMetadataAsync(request);
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.GetAllSubmissionAgreementsResponse GetAllSubmissionAgreements()
    {
        return base.Channel.GetAllSubmissionAgreements();
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.GetAllSubmissionAgreementsResponse> GetAllSubmissionAgreementsAsync()
    {
        return base.Channel.GetAllSubmissionAgreementsAsync();
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.GetAllChecksumAlgorithmsResponse GetAllChecksumAlgorithms(FormPipe.LTA.Contracts.ServiceContracts.GetAllChecksumAlgorithmsRequest request)
    {
        return base.Channel.GetAllChecksumAlgorithms(request);
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.GetAllChecksumAlgorithmsResponse> GetAllChecksumAlgorithmsAsync(FormPipe.LTA.Contracts.ServiceContracts.GetAllChecksumAlgorithmsRequest request)
    {
        return base.Channel.GetAllChecksumAlgorithmsAsync(request);
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.SystemVersionInfoResponse GetSystemVersion()
    {
        return base.Channel.GetSystemVersion();
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.SystemVersionInfoResponse> GetSystemVersionAsync()
    {
        return base.Channel.GetSystemVersionAsync();
    }
    
    public FormPipe.LTA.Contracts.ServiceContracts.RollbackIngestionResponse RollbackIngestion(FormPipe.LTA.Contracts.ServiceContracts.RollbackIngestionRequest request)
    {
        return base.Channel.RollbackIngestion(request);
    }
    
    public System.Threading.Tasks.Task<FormPipe.LTA.Contracts.ServiceContracts.RollbackIngestionResponse> RollbackIngestionAsync(FormPipe.LTA.Contracts.ServiceContracts.RollbackIngestionRequest request)
    {
        return base.Channel.RollbackIngestionAsync(request);
    }
}
